<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class User
 *
 * @package App
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property bool $active
 * @property string $activation_token
 * @property string $remember_token
 */
class User extends ReferencedModel
{
    use Authenticatable;

    const ID = 'id';
    const NAME = 'name';
    const EMAIL = 'email';
    const PASSWORD = 'password';
    const ACTIVE = 'active';
    const ACTIVATION_TOKEN = 'activation_token';
    const REMEMBER_TOKEN = 'remember_token';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        self::NAME,
        self::EMAIL,
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        self::PASSWORD,
        self::ACTIVATION_TOKEN,
        self::REMEMBER_TOKEN,
    ];

    /**
     * The questions that this user has.
     *
     * @return HasMany
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    /**
     * The answers that this user has.
     *
     * @return HasMany
     */
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    /**
     * @inheritdoc
     */
    public function getReferenceByIdOrFail(int $id) : string {

        return parent::getReferenceByIdOrFail($id);
    }

    /**
     * @inheritdoc
     */
    public function getLoadableRelations() : array {
        return [

        ];
    }

    /**
     * Manually delete child objects to cascade deletes to non-foreign key
     * children.
     *
     * @return bool|null
     */
    function delete()
    {
        if($this->solarPanels) {
            /** @var SolarPanel $solarPanel */
            foreach($this->solarPanels as $solarPanel) {
                $solarPanel->delete();
            }
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
